version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 20

  - package-ecosystem: docker
    directory: "/"
    registries: "*"
    ignore:
      - dependency-name: "eclipse-temurin*"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: monthly
    open-pull-requests-limit: 20
      
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 20

registries:
  dhi-io:
    type: docker-registry
    url: https://dhi.io
    # Tokens must be also stored unser Secrets and variables -> Dependabot 
    username: ${{ secrets.DOCKERHUB_USERNAME }}
    password: ${{ secrets.DOCKERHUB_TOKEN }}