name: Publish to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    if: ${{ false }}  # disable for now
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'
      - name: Publish package
        run: mvn -DskipTests=true -DskipITs=true --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
